server:
  port: 9002
spring:
  application:
    name: service-verification-code
  redis:
    host: 172.16.98.100
eureka:
  client:
#    enabled: false
    service-url:
      #注意，生产中如果配置集群，则集群地址顺序要打乱，因为拉取注册表只从第一个地址拉取
      defaultZone: http://eureka-7900:7900/eureka
    # 拉取注册表间隔时间
    registry-fetch-interval-seconds: 30
  instance:
    # 心跳间隔时间（续约时间，即：client发送心跳，server对该服务续约） 默认30
    lease-renewal-interval-in-seconds: 30