spring:
  application:
    name: cloud-eureka
#  CAP原则 ：一致性（Consistency）/可用性（Availability）/分区容忍性（Partition tolerance）
#  Eureka实现了AP ,存在三级缓存：register --> readWriteCaCheMap --> readOnlyCacheMap  30s同步一次 use-read-only-response-cache
eureka:
  client:
    register-with-eureka: true #是否将自己注册到eureka中
    fetch-registry: false  #是否从eureka中获取信息
    service-url:
      # 单节点 就写一个；两个节点只写另一个节点 ；三个以上节点：全部写上  。逗号分隔
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
#      defaultZone: http://localhost:7900/eureka/
#      defaultZone: http://eureka-7900:7900/eureka/,http://eureka-7901:7901/eureka/,http://eureka-7902:7902/eureka/
    registry-fetch-interval-seconds: 20 # 拉取注册表间隔时间 单位秒
  server:
    enable-self-preservation: false #Eureka自我保护机制 看服务的多少：服务很多建议开启；服务较少 则关闭
    renewal-percent-threshold: 0.85 #自我保护阈值 ，默认为0.85
    eviction-interval-timer-in-ms: 1000 # 剔除服务间隔（eureka server将长时间没有心跳的服务从注册表剔除）可以设置参数为1秒实现服务快速下线，单位：毫秒，默认60秒，
    use-read-only-response-cache: true # 是否开启从readOnly读注册表
    response-cache-update-interval-ms: 1000 #缓存同步时间（readONLYCache和readWriteCache同步时间间隔） 单位：毫秒，默认30秒，

---
server:
  port: 7900
spring:
  profiles: 7900
eureka:
  instance:
    # host文件配置
    hostname: eureka-7900
---
server:
  port: 7901
spring:
  profiles: 7901
eureka:
  instance:
    # host文件配置
    hostname: eureka-7901
---
server:
  port: 7902
spring:
  profiles: 7902
eureka:
  instance:
    # host文件配置
    hostname: eureka-7902